### ISSUE TITLE
is bootloader and modem can be separately flashable?

### ISSUE THREAD

**Issue by Kyogre** [corsicanu/9820-bootloaders_and_modems#1]
I still don't understand, how to flash modem separately, so I can stay on my current (old) bootloader, but with updated (latest) modem (so we can have ability to flash any of the old custom ROMs, but with latest modem).
Which file from "Releases" tab have we need to flash for this case?

**Comment by corsicanu** [comment]
You can't do that and it's not recommended either. Modem and bootloader has to be in sync from same firmware version, otherwise they might conflict and you will end with 00000.. imei. 
If you want to stick to a bootloader version consider sticking to that baseband too, as far as i'm concerned it won't be an issue until an future OS upgrade.
