### ISSUE TITLE
Bootlogo patcher before bootloader/modem files... stuck!

### ISSUE THREAD

**Issue by b16r05** [corsicanu/9820-bootloaders_and_modems#3]
Thank you for bootloader/modem files as well as bootlogo patch. 

On the first phone, everything went fine. On the second phone, I flashed TWRP_Bootlogo_patcher.zip first, and stupidly without rebooting, I flashed, a bootloader/modem file. Now, I cannot get past boot logo (press power key to continue). Any advice?

**Comment by b16r05** [comment]
Phone: S10e 
Bootloader/Modem: G970FXXU9FUBD-twrp_flashable

So far, I have tried: 

1. Flashing G970FXXU9FUBD-odin_flashable; get stuck on Samsung boot logo
2. Flashing twrp-3.4.0_9-3-beyond0lte.img; get stuck on Samsung boot logo
3. Flashing BWF_G970F (from here: https://forum.xda-developers.com/t/rom-lineageos-17-1-for-s10e-s10-s10-exynos.4006917/page-29#post-81770511); get stuck on the Lineage OS logo

Here is the image... please help!

![IMG_20210314_180139_proc_proc](https://user-images.githubusercontent.com/11857531/111079061-33bd6600-84f0-11eb-9a2e-eca02978af2f.jpg)

**Comment by corsicanu** [comment]
Please stop flashing random things on your phone.
Do as it follows and you'll be fine:
1. Download and flash odin package of bootloader/modems following the instructions from the readme
2. Force phone back to download mode
3. Get latest TWRP tar file from dl.twrp.me/beyond0lte
4. Download vbmeta.tar from corsica.nu/vbmeta.tar
5. Place twrp file in AP, vbmeta in CP, hit flash and press buttons to reach twrp.
6. In twrp reflash the rom of your choice or flash multidisabler if you're going to stick to stock rom
7. Only after you do a successful boot of system proceed in flashing TWRP_bootlogo_patcher and anything else you want.
As far as i see it it's not a problem of bootlogo patcher or bootloader/modem zips, it's just a glitch that will get fixed by following the above procedure.
Let me know how it goes.

**Comment by b16r05** [comment]
@corsicanu Thank you, thank you, thank you!

I had to use an SD card to load multidisabler-samsung-2.6, but other than that, it worked fine, including TWRP_bootlogo_patcher at the end! Thanks again!
